Allow accessing data by paths
anacrolix/confluence pull request #33
Opened 2021-12-20 15:52 UTC by ftk

#17
Rationale:
- HTTP clients can infer the filename by path (without even starting the download), so there is no need for `?filename=`
- Some files can refer to other files in the same directory. For example, the file is a playlist and media player now can seamlessly load other files it refers to using http.

This PR adds these endpoints:
`GET /data/infohash/<infohash in hex>/<display path of file declared in torrent info>`
`GET /data/magnet/<URI-encoded magnet link>/<display path of file declared in torrent info>`

2021-12-22 04:24 UTC, anacrolix commented on README.md
> +  `GET /data/magnet/<URI-encoded magnet link>/<display path of file declared in torrent info>`
This brings a whole new consistency problem to the library. Existing libraries unpack magnet links and update the torrent state with the magnet parameters by posting to /metainfo. If you accept magnet links here, you probably want to accept them for any handler that takes an infohash.

2021-12-22 04:24 UTC, anacrolix commented on confluence/mux.go
> +		mux.Handle("/data/", h.withTorrentContext(dataHandler))
Doens't this prevent accepting `/data`, or does it redirect it?

2021-12-22 13:56 UTC, ftk commented on confluence/mux.go
> +		mux.Handle("/data/", h.withTorrentContext(dataHandler))
It seems to 301 redirect /data?... to /data/?... for some reason.

2021-12-22 13:59 UTC, ftk commented on README.md
> +  `GET /data/magnet/<URI-encoded magnet link>/<display path of file declared in torrent info>`
Don't they already support `?magnet=<magnet URI>`? 
`.../magnet/...` and `.../infohash/...` is also supported for any torrent handler, didn't want to clutter the readme.

2021-12-22 23:38 UTC, anacrolix commented on README.md
> +  `GET /data/magnet/<URI-encoded magnet link>/<display path of file declared in torrent info>`
You're right, I have too many projects 😿 .

2021-12-22 23:39 UTC, anacrolix commented on confluence/mux.go
> +		mux.Handle("/data/", h.withTorrentContext(dataHandler))
That's behaviour of the standard lib http.ServeMux I think. There are a lot of projects already depending on the existing behaviour, I don't think I want to change this in the short-term.

2021-12-22 23:40 UTC, anacrolix commented
@boramalper what do you think of this PR?

2021-12-28 20:03 UTC, boramalper commented
I haven't personally tested it, but looks good to me. 👍

2021-12-29 04:13 UTC, anacrolix requested changes

2021-12-29 04:13 UTC, anacrolix commented on confluence/mux.go
> +		mux.Handle("/data/", h.withTorrentContext(dataHandler))
This will need to be addressed to consider merging.

2022-01-06 21:03 UTC, anacrolix commented
I might make a few changes on top of the PR, let me know your thoughts on the changes. Sorry for the pedanticism but this is used heavily and very specifically by a lot of production services.

2022-01-06 22:30 UTC, anacrolix commented
@ftk what do you think of https://github.com/anacrolix/confluence/pull/34? It refactors some stuff to make the changes in this PR fit in more in the style of this module, and makes it easier to adapt to other routes down the track (including potentially magnet and host name handling).

2022-01-07 13:26 UTC, ftk commented
Thanks! I'll close this in favor of #34.

2022-01-07 13:26 UTC, closed without merging